name: Fetch Cleaned Data

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pytz
    
    - name: Fetch and convert data
      run: python scripts/fetch_sheets.py
    
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update index.html from Google Sheets" && git push) 
